#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ] && [ "$SKIP_BREW" != "1" ]; then
  brew bundle check >/dev/null 2>&1 || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

# Check Node version
INSTALLED_NODE_VERSION=$(node -v)
if [ -z "$INSTALLED_NODE_VERSION" ]; then
  echo "Node.js is not installed. Please install it"
  exit 1
elif [ "$(printf '$INSTALLED_NODE_VERSION\n$REQUIRED_NODE_VERSION' | sort -V | head -n1)" != "$REQUIRED_NODE_VERSION" ]; then
  echo "Node.js version $REQUIRED_NODE_VERSION or greater is required. Found: $INSTALLED_NODE_VERSION"
  exit 1
fi

# Clean npm/yarn cache before installing
echo "==> Clearing npm/yarn cache..."
$PACKAGE_MANAGER cache clean --force

# Install dependencies
echo "==> Installing Node dependencies…"
PACKAGE_MANAGER=$(command -v yarn >/dev/null 2>&1 && echo "yarn" || echo "npm")

$PACKAGE_MANAGER install

# Optionally run tests
echo "==> Running tests..."
$PACKAGE_MANAGER run test
